
name: Test carry.team

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/10  * * * *'


jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          python -m pip install selenium
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
        with:
          chrome-version: 97.0.4692.36
      - name: Run Tests    
        run: python -m unittest TestCases.py
